/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package running;

import javax.swing.JPanel;
import main.MainFrame;
import main.ReturnHandler;
/**
 *
 * @author Stalin
 */
public class PersonalizadoPanel extends javax.swing.JPanel implements ReturnHandler{
    private MainFrame mainframe;
 
    public PersonalizadoPanel(MainFrame mainframe) {
        this.mainframe = mainframe;
        initComponents();
    }
    /**
     * Creates new form PersonalizadoPanel
     */
    public PersonalizadoPanel() {
        initComponents();
    } /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTiempo = new javax.swing.JLabel();
        lblVelocidad = new javax.swing.JLabel();
        lblInclinacion = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        txtVelocidad = new javax.swing.JTextField();
        txtInclinacion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        actionBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        lblTiempo.setText("Tiempo");

        lblVelocidad.setText("Velocidad");

        lblInclinacion.setText("Inclinacion");

        actionBtn.setBackground(new java.awt.Color(92, 161, 2));
        actionBtn.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        actionBtn.setForeground(new java.awt.Color(255, 255, 255));
        actionBtn.setText("Iniciar rutina");
        actionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInclinacion)
                    .addComponent(lblVelocidad)
                    .addComponent(lblTiempo)
                    .addComponent(txtTiempo)
                    .addComponent(txtVelocidad)
                    .addComponent(txtInclinacion, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTiempo)
                .addGap(18, 18, 18)
                .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblVelocidad)
                .addGap(24, 24, 24)
                .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInclinacion)
                .addGap(18, 18, 18)
                .addComponent(txtInclinacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionBtnActionPerformed
        // TODO add your handling code here:
        mainframe.setMainPanel(new RutinaEnCurso(mainframe)); 
    }//GEN-LAST:event_actionBtnActionPerformed

    @Override
    public void doReturnAction() {
        mainframe.setMainPanel(new RunningPanel(mainframe)); //To change body of generated methods, choose Tools | Templates.
    }
    @Override
    public JPanel getReference() {
        return this;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInclinacion;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JTextField txtInclinacion;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
