/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package running;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.MainFrame;
import main.ReturnHandler;

/**
 *
 * @author Stalin
 */
public class PersonalizadoPanel extends javax.swing.JPanel implements ReturnHandler {

    private MainFrame mainframe;

    public PersonalizadoPanel(MainFrame mainframe) {
        this.mainframe = mainframe;
        initComponents();
    }

    /**
     * Creates new form PersonalizadoPanel
     */
    public PersonalizadoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTiempo = new javax.swing.JLabel();
        lblVelocidad = new javax.swing.JLabel();
        lblInclinacion = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        actionBtn = new javax.swing.JButton();
        cmbVelocidad = new javax.swing.JComboBox<>();
        cmbInclinacion = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        lblTiempo.setText("Tiempo (min)");

        lblVelocidad.setText("Nivel Velocidad");

        lblInclinacion.setText("Nivel Inclinación");

        txtTiempo.setForeground(new java.awt.Color(226, 135, 67));
        txtTiempo.setToolTipText("El tiempo recomendado es 30 minutos.");

        actionBtn.setBackground(new java.awt.Color(226, 135, 67));
        actionBtn.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        actionBtn.setForeground(new java.awt.Color(255, 255, 255));
        actionBtn.setText("Iniciar rutina");
        actionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cmbVelocidad.setForeground(new java.awt.Color(226, 135, 67));
        cmbVelocidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbVelocidad.setSelectedIndex(-1);

        cmbInclinacion.setForeground(new java.awt.Color(226, 135, 67));
        cmbInclinacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "20", "40" }));
        cmbInclinacion.setSelectedIndex(-1);

        txtTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setText("Rutina Personalizada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVelocidad)
                        .addGap(18, 18, 18)
                        .addComponent(cmbVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTiempo)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblInclinacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbInclinacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblTiempo)
                .addGap(18, 18, 18)
                .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelocidad)
                    .addComponent(cmbVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInclinacion)
                    .addComponent(cmbInclinacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtTiempo.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void actionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionBtnActionPerformed
        // TODO add your handling code here:
        double tiempo;
        int inclinacion, velocidad;

        if (txtTiempo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Valor tiempo vacio!");
        } else {
            try {
                tiempo = Double.parseDouble(txtTiempo.getText());
                if (tiempo <= 0) {
                    JOptionPane.showMessageDialog(null, "No se admiten valores negativos");
                } else {
                    if (cmbVelocidad.getSelectedIndex() != -1 || cmbInclinacion.getSelectedIndex() != -1) {
                        velocidad = cmbVelocidad.getSelectedIndex() + 1;
                        inclinacion = cmbInclinacion.getSelectedIndex();
                        System.out.println(velocidad);
                        mainframe.getAplicacion().seleccionarRunning().seleccionarPersonalizada().obtenerDatos(tiempo, velocidad, inclinacion);
                        mainframe.getAplicacion().seleccionarRunning().seleccionarPersonalizada().iniciar();
                        System.out.println(mainframe.getAplicacion().seleccionarRunning().seleccionarPersonalizada().getCaloriasQuemadas());

                        mainframe.setMainPanel(new RutinaEnCursoPersonalizado(mainframe));
                    }else{JOptionPane.showMessageDialog(null, "Debe seleccionar velocidad e inclinación ");}
                }
            } catch (NumberFormatException e) {
                if (esNumero(txtTiempo.getText()) == false) {
                    JOptionPane.showMessageDialog(null, "Valor de tiempo incorrecto!");
                }
            }
        }
        //mainframe.setMainPanel(new RutinaEnCursoPersonalizado(mainframe));     
    }//GEN-LAST:event_actionBtnActionPerformed

    @Override
    public void doReturnAction() {
        mainframe.setMainPanel(new RunningPanel(mainframe)); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public JPanel getReference() {
        return this;
    }

    public boolean esNumero(String str) {

        return str.matches("[+-]?\\d*(\\.\\d+)?");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionBtn;
    private javax.swing.JComboBox<String> cmbInclinacion;
    private javax.swing.JComboBox<String> cmbVelocidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInclinacion;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
