/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package running;
 
import javax.swing.JPanel;
import main.MainFrame;
import main.ReturnHandler;
 
/**
 *
 * @author Stalin
 */
public class RunningPanel extends javax.swing.JPanel implements ReturnHandler {
     MainFrame mainframe;
    public RunningPanel(MainFrame mainframe) {
        
        this.mainframe = mainframe;
        initComponents();
    }
    /**
     * Creates new form RunningPanel
     */
    public RunningPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRutinaEstandar = new javax.swing.JToggleButton();
        btnRutinaPersonalizada = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        btnRutinaEstandar.setText("Estandar");
        btnRutinaEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutinaEstandarActionPerformed(evt);
            }
        });

        btnRutinaPersonalizada.setText("Personalizada");

        jLabel1.setText("Seleccione el tipo de rutina:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnRutinaEstandar)
                        .addGap(33, 33, 33)
                        .addComponent(btnRutinaPersonalizada))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRutinaEstandar)
                    .addComponent(btnRutinaPersonalizada))
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRutinaEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutinaEstandarActionPerformed
        // TODO add your handling code here:
        
    //TiempoPanel panel1 = new TiempoPanel();
    //panel1.setSize(500, 500);
    //panel1.setLocation(0, 0);
    
    //mainframe.setMainPanel(new panel1(mainframe));
     
        
        
    }//GEN-LAST:event_btnRutinaEstandarActionPerformed
    //private void mostrarPanelEstandarRunning(MainFrame mainframe){
    //mainFrame.setMainPanel(new RunningPanel(mainFrame));
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnRutinaEstandar;
    private javax.swing.JToggleButton btnRutinaPersonalizada;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    //hoa
    @Override
    public void doReturnAction() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public JPanel getReference() {
         return this;
    }
}
