/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package running;
 
import javax.swing.JPanel;
import main.ActividadesPane;
import main.MainFrame;
import main.ReturnHandler;

import running.TiempoPanel;
import running.PersonalizadoPanel;
 
/**
 *
 * @author Stalin
 */
public class RunningPanel extends javax.swing.JPanel implements ReturnHandler {
     MainFrame mainframe;
    public RunningPanel(MainFrame mainframe) {
        
        this.mainframe = mainframe;
        initComponents();
    }
    /**
     * Creates new form RunningPanel
     */
    public RunningPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRutinaEstandar = new javax.swing.JToggleButton();
        btnRutinaPersonalizada = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        btnRutinaEstandar.setBackground(new java.awt.Color(232, 159, 105));
        btnRutinaEstandar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRutinaEstandar.setForeground(new java.awt.Color(255, 255, 255));
        btnRutinaEstandar.setText("Estandar");
        btnRutinaEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutinaEstandarActionPerformed(evt);
            }
        });

        btnRutinaPersonalizada.setBackground(new java.awt.Color(226, 135, 67));
        btnRutinaPersonalizada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRutinaPersonalizada.setForeground(new java.awt.Color(255, 255, 255));
        btnRutinaPersonalizada.setText("Personalizada");
        btnRutinaPersonalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutinaPersonalizadaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione el tipo de rutina:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRutinaEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRutinaPersonalizada, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRutinaEstandar, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(btnRutinaPersonalizada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRutinaEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutinaEstandarActionPerformed
    mainframe.setMainPanel(new TiempoPanel(mainframe));  
    }//GEN-LAST:event_btnRutinaEstandarActionPerformed

    private void btnRutinaPersonalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutinaPersonalizadaActionPerformed
        // TODO add your handling code here:
        mainframe.setMainPanel(new PersonalizadoPanel(mainframe)); 
    }//GEN-LAST:event_btnRutinaPersonalizadaActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnRutinaEstandar;
    private javax.swing.JToggleButton btnRutinaPersonalizada;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    //hoa
    @Override
    public void doReturnAction() {
         mainframe.setMainPanel(new ActividadesPane(mainframe));
    }

    @Override
    public JPanel getReference() {
         return this;
    }
}
