/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package running;

import main.MainFrame;

/**
 *
 * @author Stalin
 */
public class TiempoPanel extends javax.swing.JPanel {

    /**
     * Creates new form TiempoPanel
     */
    public TiempoPanel() {
        initComponents();
    }

    TiempoPanel(MainFrame mainframe) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTiempo1 = new javax.swing.JToggleButton();
        btnTiempo3 = new javax.swing.JToggleButton();
        btnTiempo2 = new javax.swing.JToggleButton();

        btnTiempo1.setText("10");

        btnTiempo3.setText("25");

        btnTiempo2.setText("15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTiempo3)
                    .addComponent(btnTiempo2)
                    .addComponent(btnTiempo1))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnTiempo1)
                .addGap(12, 12, 12)
                .addComponent(btnTiempo2)
                .addGap(18, 18, 18)
                .addComponent(btnTiempo3)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnTiempo1;
    private javax.swing.JToggleButton btnTiempo2;
    private javax.swing.JToggleButton btnTiempo3;
    // End of variables declaration//GEN-END:variables
}
